### ISSUE TITLE
Garage door sensor - Unable to set alarm time

### ISSUE THREAD

**Issue by blendedmedia** [priknr1/com.visionsecurity#12]
**Vision Security v1.4.2**
**Homey Firmware Version: 1.5.12**

I try to change the alarm time value from 0 to 1 second. If not, I guess the alarm will stay "ON" forever when it goes off?
But when I try to save my changes it takes forever and always end up with a dialog saying "Homey offline":
![Image of error message](https://snag.gy/92ZliJ.jpg)

After that the Vision App crashes...
![Image of error dialog message](https://snag.gy/0MxfR8.jpg)

I've sent the crash report to the developer (you?).

Thanks in advance.

**Comment by priknr1** [comment]
This device does not hve any settings, it is a copy paste error of mine. I will remove them
