### ISSUE TITLE
Please add 4in1 PIR Sensor (ZP3111EU-5)

### ISSUE THREAD

**Issue by madmax75** [priknr1/com.visionsecurity#2]
4in1 PIR Sensor:

Brand: Vision
Identifier: ZP3111EU-5
Manufacturer ID: 0x0109
Product Type ID: 0x2021
Product ID: 0x2101

**Comment by priknr1** [comment]
I added your device, had to go blind, since little needed documentation, and also dont have the sensor myself. The update (1.2.3) should be in the appstore within days. If things work, and you feel like it, you can always donate me a beer or something with the donate button in the readme.

Please let me know when you where able to test, and if things are working

**Comment by lgaerd** [comment]
The sensor works very well. Many thanks. All functions are ok.
Is it possible to set/edit the device specific settings?

The english instruction text in the app.json should be adjusted for inclusion:
"En": "Push the switch on the botton"

I have modified the icon.svg and learnmode.svg.
Enclosed a new icon.svg and learnmode.svg.
[zp3111.zip](https://github.com/priknr1/com.visionsecurity/files/1060592/zp3111.zip)

**Comment by priknr1** [comment]
I will have a look at the settings.

**Comment by lgaerd** [comment]
Ok great, i think bottom is not the same as the back of the device

**Comment by priknr1** [comment]
Yes, you are right, I was thinking of the device lying down, than back is same as bottom.  But you are right.

**Comment by priknr1** [comment]
I added the settings, 1.2.4 is now pending in the appstore, so will be available within days.
Please let me know if things are okay so i can close this thread.

**Comment by madmax75** [comment]
I will test it today

**Comment by madmax75** [comment]
I have tested the version 1.2.4. The LED mode does not work properly. If I disable the LED mode, the sensor still flashes. The other settings are ok. 
I have made two pull requests. Please check this...
