### ISSUE TITLE
DC/AC power siren not available in flow editor

### ISSUE THREAD

**Issue by ivostakenborg** [priknr1/com.visionsecurity#5]
Hi Patrick,

The Vision DC/AC Power Siren is still not available in the flow editor. I can see the device in 'My devices' and I can turn it on. It's also available as a Tag in the flow editor. Removing the device and reconnecting isn't solving the problem. A hard refresh won't fix it and the device isn't added under another name. Do you have any idea what i can do to resolve this issue?

Thanks for your response!

Ivo
![2018-03-10 19_38_04-flow - homey](https://user-images.githubusercontent.com/28729434/37245587-b68de456-249a-11e8-889c-e00e11358736.png)
![2018-03-10 19_38_19-flow - homey](https://user-images.githubusercontent.com/28729434/37245588-b6aaa8b6-249a-11e8-8221-3bab58efc0a3.png)
![2018-03-10 19_37_00-zones devices - homey](https://user-images.githubusercontent.com/28729434/37245589-b6c6beb6-249a-11e8-83c1-26691ee1ec3d.png)
![2018-03-10 19_37_41-flow - homey](https://user-images.githubusercontent.com/28729434/37245590-b6e30788-249a-11e8-8fb0-c6593eed3dd1.png)

**Comment by priknr1** [comment]
@ivostakenborg   Sorry, I did not see this message before. Should be available from version 1.4.4 and up
