### ISSUE TITLE
My garage door sensor is not working

### ISSUE THREAD

**Issue by rowins** [priknr1/com.visionsecurity#6]
I was wondering why my garage door sensor is adding as an unknown Z-Wave device.
Can I fix this problem? Every other Z-Wave device works fine.

I have vision app V 1.4.2
Homey firmware V 1.5.11

Device information at my homey:
![image](https://user-images.githubusercontent.com/28347698/42040050-12269a9c-7aef-11e8-9d44-0473b0583126.png)

**Comment by priknr1** [comment]
I havent been active on here for a long time. Is this still an issue for you? Or can I close it?

**Comment by Klockan3** [comment]
How was this solved?
