### ISSUE TITLE
Door/windows sensor not working well on homey

### ISSUE THREAD

**Issue by ManuelvanStrien** [priknr1/com.visionsecurity#7]
I succesfully added the vision door/window sensor to homey, it is visible in the device list, but after a few minutes the icon changes to the 'broken' icon and it says 'invalid command class' and stops working.

help?

**Comment by Klasseman** [comment]
Do you solved problem?

**Comment by priknr1** [comment]
This is most likely the same problem as Klasseman's, I will continue in that issue, and close this one
