### ISSUE TITLE
Cannot add ZM1602

### ISSUE THREAD

**Issue by pln8421** [priknr1/com.visionsecurity#8]
Hello.
I had this included in my Vera3 and it worked fine.
It was excluded from Vera and I now try to include it into Homey.
I choose AC/DC device.
It seems that gets included but Home cannot find it and I cannot see it. When I later try to include it says Its already paired. Try to remove device in settings. I have done this 20 times but when try to add nothing is shown. Homey cannot find it... and I cannot see it in device list.
I even removed the inbuilt battery for 2 days

**Comment by priknr1** [comment]
I assume this is the same issue as you posted this week, so will hterfor close this one

**Comment by pln8421** [comment]
Hello Patrick.
Thanks for the answer. I made a comment on Github. #17
Here are the pictures.
[Image]
[Image]
[Image]
[Image]
[Image]
[Image]
[Image]
[Image]
[Image]
[Image]
Best regards Per

________________________________
Från: Patrick <notifications@github.com>
Skickat: tisdag, februari 19, 2019 14:48
Till: priknr1/com.visionsecurity
Kopia: pln8421; Author
Ämne: Re: [priknr1/com.visionsecurity] Cannot add ZM1602 (#8)


I assume this is the same issue as you posted this week, so will hterfor close this one
